os:
  - linux
  - osx
language: ruby
sudo: false
rvm:
  # We use language features of Ruby that are not supported in Ruby 1.9.x or
  # older.
  #- 1.8.7
  #- 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.2.1
  - 2.3.1
  - 2.2.5
  - 2.3.3
  - 2.4.0
  - 2.5.1
matrix:
  exclude:
    - os: osx
      rvm: 1.9.3
    - os: osx
      rvm: 2.0.0
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew bundle; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which dpkg-deb || 'dpkg-deb not found'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which lintian || echo 'lintian not found'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which python || brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which easy_install || echo 'easy_install not found'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which virtualenv || pip install --user virtualenv ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then which virtualenv-tools || pip install --user virtualenv virtualenv-tools ; fi
  - virtualenv ${HOME}/.venv
script: source ${HOME}/.venv/bin/activate && PATH=${PATH}:${HOME}/.local/bin bundle exec rspec
addons:
  apt:
    packages:
      - bsdtar
      - rpm
      - lintian
      - python-setuptools
      - python-pip
      - squashfs-tools
