language: ruby
sudo: false
rvm:
  # We use language features of Ruby that are not supported in Ruby 1.9.x or
  # older.
  #- 1.8.7
  #- 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.2.1
script: bundle exec rspec
addons:
  apt:
    packages:
      - bsdtar
      - rpm
      - lintian
